# Generated by Django 4.1.11 on 2023-12-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_rename_tags_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
