# Generated by Django 4.1.11 on 2024-02-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_content_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
