# Generated by Django 4.1.11 on 2024-03-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.TextField(),
        ),
    ]
