# Generated by Django 4.1.11 on 2024-03-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="a", unique=True),
            preserve_default=False,
        ),
    ]
