# Generated by Django 4.1.11 on 2023-11-14 06:49

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[users.validators.validate_username],
            ),
        ),
    ]
