# Generated by Django 4.1.11 on 2023-12-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="liked",
            field=models.BooleanField(default=False),
        ),
    ]
