# Generated by Django 4.1.11 on 2023-12-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0002_like_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="disliked",
            field=models.BooleanField(default=False),
        ),
    ]
