# Generated by Django 4.1.11 on 2023-12-06 06:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0003_like_disliked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="disliked",
        ),
    ]
