name: CI

on:
    push:
        branches:
            - '*'
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        
        env:
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            DB_ENGINE: ${{ secrets.DB_ENGINE }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_HOST: ${{ secrets.DB_HOST }}

        steps:
        - name: Checkout code
        - uses: actions/checkout@v4
        - run: mysql -h ${{ secrets.DB_HOST }} --port ${{ secrets.DB_PORT }} -p${{ secrets.DB_PASSWORD }};
