name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        PYTHON_VERSION: "3.10"

    services:
        mysql:
            image: mysql:latest
            env:
                MYSQL_DATABASE: ${{ secrets.DB_NAME }}
                MYSQL_USER: ${{ secrets.DB_USER }}
                MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
                MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
            ports:
                - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - uses: browser-actions/setup-firefox@v1
    - run: firefox --version

    - name: Set up Geckodriver
      run: |
        GECKODRIVER_VERSION="latest"
        wget "https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz"
        tar -xvzf geckodriver-v0.34.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Start MySQL Service
      run: sudo systemctl start mysql

    - name: Initialize Database
      run: |
        mysql -h localhost -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"

    - name: Run tests
      env:
        DB_ENGINE: ${{ secrets.DB_ENGINE }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: localhost
        DB_PORT: 3306
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        python manage.py test


