name: CI

on:
  push:
  workflow_dispatch:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        PYTHON_VERSION: "3.10"
    services:
        mysql:
            image: mysql:latest
            env:
                DB_ENGINE: ${{ secrets.DB_ENGINE }}
                DB_USER: ${{ secrets.DB_USER }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_NAME: ${{ secrets.DB_NAME }}
                DB_HOST: ${{ secrets.DB_HOST }}
            ports:
                - 8000
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_ENGINE: ${{ secrets.DB_ENGINE }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PORT: 8000
      run: |
        sudo /etc/init.d/mysql start
        python manage.py test
