name: CI

on:
    push:
        branches:
            - '*'
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: python manage.py test

        - name: Lint code
          run: flake8 .

        - name: Check migrations
          run: python manage.py makemigrations --check --dry-run
